# Facebook Engagement Analysis - Exploratory Data Analysis

Author: Nick Peril 
Project: TKH Phase I Portfolio  
Dataset: Facebook Metrics (UCI Repository)

## Objective
To explore the dataset and identify patterns that influence post engagement.

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Loading my dataset:

In [8]:
df = pd.read_csv("/Users/saadult/facebook-engagement-analysis/data/raw/dataset_Facebook.csv")

Displaying the first 20 rows:

In [9]:
df. head(20)

   Page total likes;Type;Category;Post Month;Post Weekday;Post Hour;Paid;Lifetime Post Total Reach;Lifetime Post Total Impressions;Lifetime Engaged Users;Lifetime Post Consumers;Lifetime Post Consumptions;Lifetime Post Impressions by people who have liked your Page;Lifetime Post reach by people who like your Page;Lifetime People who have liked your Page and engaged with your post;comment;like;share;Total Interactions
0   139441;Photo;2;12;4;3;0;2752;5091;178;109;159;...
1   139441;Status;2;12;3;10;0;10460;19057;1457;136...
2   139441;Photo;3;12;3;3;0;2413;4373;177;113;154;...
3   139441;Photo;2;12;2;10;1;50128;87991;2211;790;...
4   139441;Photo;2;12;2;3;0;7244;13594;671;410;580...
5   139441;Status;2;12;1;9;0;10472;20849;1191;1073...
6   139441;Photo;3;12;1;3;1;11692;19479;481;265;36...
7   139441;Photo;3;12;7;9;1;13720;24137;537;232;30...
8   139441;Status;2;12;7;3;0;11844;22538;1530;1407...
9   139441;Photo;3;12;6;10;0;4694;8668;280;183;250...
10  139441;Status;2;12;5;10;0;21744;42334;4258;410...
11  139441;Photo;2;12;5;10;0;3112;5590;208;127;145...
12  139441;Photo;2;12;5;10;0;2847;5133;193;115;133...
13  139441;Photo;2;12;5;3;0;2549;4896;249;134;168;...
14  138414;Photo;2;12;4;5;1;22784;39941;887;337;41...
15  138414;Status;2;12;3;10;0;10060;19680;1264;120...
16  138414;Photo;3;12;3;3;0;1722;2981;163;123;148;...
17  138414;Photo;1;12;2;12;1;53264;111785;1706;110...
18  138414;Status;3;12;2;3;0;3930;7509;130;86;112;...
19  138414;Photo;3;12;1;11;0;1591;2825;121;88;111;...

In [10]:
df.shape

(500, 1)

The dataset contains 500 rows and only 1 column.

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                                                                             Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                                                                                                                                                             --------------  -----
 0   Page total likes;Type;Category;Post Month;Post Weekday;Post Hour;Paid;Lifetime Post Total Reach;Lifetime Post Total Impressions;Lifetime Engaged Users;Lifetime Post Consumers;Lifetime Post Consumptions;Lifetime Post Impressions by people who have liked your Page;Lifetime Post reach by people who like your Page;Lifetime People who have liked your Page and engaged with your post;comment;like;share;Total Interactions  500 non-null    object
dtypes: object(1)
memory usage: 4.0+ KB

In [12]:
df.describe()

       Page total likes;Type;Category;Post Month;Post Weekday;Post Hour;Paid;Lifetime Post Total Reach;Lifetime Post Total Impressions;Lifetime Engaged Users;Lifetime Post Consumers;Lifetime Post Consumptions;Lifetime Post Impressions by people who have liked your Page;Lifetime Post reach by people who like your Page;Lifetime People who have liked your Page and engaged with your post;comment;like;share;Total Interactions
count                                                 500
unique                                                500
top     139441;Photo;2;12;4;3;0;2752;5091;178;109;159;...
freq                                                    1